version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.develop

    restart: always
    volumes:
      - .:/app
    
    networks:
      - net_api      
    ports:
      - 5000:5000
  
    

networks:
  net_api:    
  

