# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movies.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='movies.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cmovies.proto\"\"\n\x06Genres\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\"\n\x0fMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1b\n\x07MovieId\x12\x10\n\x08movie_id\x18\x01 \x01(\x05\"-\n\x0eGetMoviesParam\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\"Y\n\nMoviesData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x61\x64ult\x18\x02 \x01(\x08\x12\x10\n\x08language\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12\x0f\n\x07success\x18\x05 \x01(\x08\"\x88\x01\n\nMoviesList\x12\x1b\n\x06movies\x18\x01 \x03(\x0b\x32\x0b.MoviesData\x12\x13\n\x0b\x61\x63tual_page\x18\x02 \x01(\x05\x12\x13\n\x0btotal_pages\x18\x03 \x01(\x05\x12\r\n\x05itens\x18\x04 \x01(\x05\x12\x13\n\x0btotal_itens\x18\x05 \x01(\x03\x12\x0f\n\x07success\x18\x06 \x01(\x08\"n\n\x06Movies\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x61\x64ult\x18\x02 \x01(\x08\x12\x10\n\x08language\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12\x17\n\x06genres\x18\x05 \x03(\x0b\x32\x07.Genres\x12\x0f\n\x07success\x18\x06 \x01(\x08\"\x1f\n\x04\x44\x61ta\x12\x17\n\x06movies\x18\x01 \x03(\x0b\x32\x07.Movies2\x88\x01\n\rMoviesService\x12+\n\tGetMovies\x12\x0f.GetMoviesParam\x1a\x0b.MoviesList\"\x00\x12\x1f\n\x08GetMovie\x12\x08.MovieId\x1a\x07.Movies\"\x00\x12)\n\x0cUpdateMovies\x12\x05.Data\x1a\x10.MessageResponse\"\x00\x62\x06proto3'
)




_GENRES = _descriptor.Descriptor(
  name='Genres',
  full_name='Genres',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Genres.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='Genres.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=50,
)


_MESSAGERESPONSE = _descriptor.Descriptor(
  name='MessageResponse',
  full_name='MessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='MessageResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=86,
)


_MOVIEID = _descriptor.Descriptor(
  name='MovieId',
  full_name='MovieId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='movie_id', full_name='MovieId.movie_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=115,
)


_GETMOVIESPARAM = _descriptor.Descriptor(
  name='GetMoviesParam',
  full_name='GetMoviesParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='GetMoviesParam.page', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='limit', full_name='GetMoviesParam.limit', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=162,
)


_MOVIESDATA = _descriptor.Descriptor(
  name='MoviesData',
  full_name='MoviesData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='MoviesData.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='adult', full_name='MoviesData.adult', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='language', full_name='MoviesData.language', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='MoviesData.title', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='success', full_name='MoviesData.success', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=253,
)


_MOVIESLIST = _descriptor.Descriptor(
  name='MoviesList',
  full_name='MoviesList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='movies', full_name='MoviesList.movies', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='actual_page', full_name='MoviesList.actual_page', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_pages', full_name='MoviesList.total_pages', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itens', full_name='MoviesList.itens', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_itens', full_name='MoviesList.total_itens', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='success', full_name='MoviesList.success', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=392,
)


_MOVIES = _descriptor.Descriptor(
  name='Movies',
  full_name='Movies',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Movies.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='adult', full_name='Movies.adult', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='language', full_name='Movies.language', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='Movies.title', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='genres', full_name='Movies.genres', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='success', full_name='Movies.success', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=504,
)


_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='movies', full_name='Data.movies', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=506,
  serialized_end=537,
)

_MOVIESLIST.fields_by_name['movies'].message_type = _MOVIESDATA
_MOVIES.fields_by_name['genres'].message_type = _GENRES
_DATA.fields_by_name['movies'].message_type = _MOVIES
DESCRIPTOR.message_types_by_name['Genres'] = _GENRES
DESCRIPTOR.message_types_by_name['MessageResponse'] = _MESSAGERESPONSE
DESCRIPTOR.message_types_by_name['MovieId'] = _MOVIEID
DESCRIPTOR.message_types_by_name['GetMoviesParam'] = _GETMOVIESPARAM
DESCRIPTOR.message_types_by_name['MoviesData'] = _MOVIESDATA
DESCRIPTOR.message_types_by_name['MoviesList'] = _MOVIESLIST
DESCRIPTOR.message_types_by_name['Movies'] = _MOVIES
DESCRIPTOR.message_types_by_name['Data'] = _DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Genres = _reflection.GeneratedProtocolMessageType('Genres', (_message.Message,), {
  'DESCRIPTOR' : _GENRES,
  '__module__' : 'movies_pb2'
  # @@protoc_insertion_point(class_scope:Genres)
  })
_sym_db.RegisterMessage(Genres)

MessageResponse = _reflection.GeneratedProtocolMessageType('MessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGERESPONSE,
  '__module__' : 'movies_pb2'
  # @@protoc_insertion_point(class_scope:MessageResponse)
  })
_sym_db.RegisterMessage(MessageResponse)

MovieId = _reflection.GeneratedProtocolMessageType('MovieId', (_message.Message,), {
  'DESCRIPTOR' : _MOVIEID,
  '__module__' : 'movies_pb2'
  # @@protoc_insertion_point(class_scope:MovieId)
  })
_sym_db.RegisterMessage(MovieId)

GetMoviesParam = _reflection.GeneratedProtocolMessageType('GetMoviesParam', (_message.Message,), {
  'DESCRIPTOR' : _GETMOVIESPARAM,
  '__module__' : 'movies_pb2'
  # @@protoc_insertion_point(class_scope:GetMoviesParam)
  })
_sym_db.RegisterMessage(GetMoviesParam)

MoviesData = _reflection.GeneratedProtocolMessageType('MoviesData', (_message.Message,), {
  'DESCRIPTOR' : _MOVIESDATA,
  '__module__' : 'movies_pb2'
  # @@protoc_insertion_point(class_scope:MoviesData)
  })
_sym_db.RegisterMessage(MoviesData)

MoviesList = _reflection.GeneratedProtocolMessageType('MoviesList', (_message.Message,), {
  'DESCRIPTOR' : _MOVIESLIST,
  '__module__' : 'movies_pb2'
  # @@protoc_insertion_point(class_scope:MoviesList)
  })
_sym_db.RegisterMessage(MoviesList)

Movies = _reflection.GeneratedProtocolMessageType('Movies', (_message.Message,), {
  'DESCRIPTOR' : _MOVIES,
  '__module__' : 'movies_pb2'
  # @@protoc_insertion_point(class_scope:Movies)
  })
_sym_db.RegisterMessage(Movies)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'movies_pb2'
  # @@protoc_insertion_point(class_scope:Data)
  })
_sym_db.RegisterMessage(Data)



_MOVIESSERVICE = _descriptor.ServiceDescriptor(
  name='MoviesService',
  full_name='MoviesService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=540,
  serialized_end=676,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMovies',
    full_name='MoviesService.GetMovies',
    index=0,
    containing_service=None,
    input_type=_GETMOVIESPARAM,
    output_type=_MOVIESLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetMovie',
    full_name='MoviesService.GetMovie',
    index=1,
    containing_service=None,
    input_type=_MOVIEID,
    output_type=_MOVIES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateMovies',
    full_name='MoviesService.UpdateMovies',
    index=2,
    containing_service=None,
    input_type=_DATA,
    output_type=_MESSAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MOVIESSERVICE)

DESCRIPTOR.services_by_name['MoviesService'] = _MOVIESSERVICE

# @@protoc_insertion_point(module_scope)
